version: "3.7"
services:
  user:
    build:
      context: ./
      dockerfile: user/Dockerfile
    image: grpc-microservices/user
    container_name: user
    ports:
      - "50051:50051"
    environment:
      - "PROJECT_SERVICE_ADDR=project:50051"
  project:
    build:
      context: ./
      dockerfile: project/Dockerfile
    image: grpc-microservices/project
    container_name: project
    ports:
      - "50052:50051"
    environment:
      - "USER_SERVICE_ADDR=user:50051"
      - "ACTIVITY_SERVICE_ADDR=activity:50051"
  task:
    build:
      context: ./
      dockerfile: task/Dockerfile
    image: grpc-microservices/task
    container_name: task
    ports:
      - "50053:50051"
    environment:
      - "PROJECT_SERVICE_ADDR=project:50051"
      - "ACTIVITY_SERVICE_ADDR=activity:50051"
  activity:
    build:
      context: ./
      dockerfile: activity/Dockerfile
    image: grpc-microservices/activity
    container_name: activity
    ports:
      - "50054:50051"
    environment:
      - "USER_SERVICE_ADDR=user:50051"
  front:
    build:
      context: ./
      dockerfile: front/Dockerfile
    image: grpc-microservices/front
    container_name: front
    ports:
      - "8080:8080"
    environment:
      - "USER_SERVICE_ADDR=user:50051"
      - "PROJECT_SERVICE_ADDR=project:50051"
      - "TASK_SERVICE_ADDR=task:50051"
      - "ACTIVITY_SERVICE_ADDR=activity:50051"
